# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:

  # Maintain dependencies for GitHub Actions
  - package-ecosystem: "github-actions"
    # Location of .github/workflows
    directory: "/"
    schedule:
      interval: "daily"

  # Maintain dependencies for Python programs
  - package-ecosystem: "pip"
    # Location of ScrapingToolKit requirements.txt
    directory: "/ScrapingToolKit/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    # Location of ada requirements.txt
    directory: "/ada/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    # Location of migration requirements.txt
    directory: "/migration/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    # Location of rack-ui requirements.txt
    directory: "/rack-ui/"
    schedule:
      interval: "monthly"
  - package-ecosystem: "pip"
    # Location of tests requirements.txt
    directory: "/tests/"
    schedule:
      interval: "monthly"
