#!/usr/bin/env bash

. $(dirname "$0")/rackfuncs.sh

outf=$(pwd)/.make.rack
tool=$(basename "$0")
realtool=$(find_in_path_remainder "$tool")
nonce="n$(date +%s)-$$"

# This flag can be used by the databin handlers of the commands
# invoked by make to link those commands to this make process.
export MAKE_DATABIN="${outf}@${nonce}:${MAKE_DATABIN}"

(
    echo ":- multifile build_with/5, build_from/2, build_inputs/2, build_outputs/2, build_start/2, build_finished/3, build_step/2."
    # shellcheck disable=SC2086
    echo "build_with(${nonce@Q}, make," ${tool@Q}, ${realtool@Q}, [ "${*@Q}" ] ")."
    # shellcheck disable=SC2027,SC2046
    echo "build_from(${nonce@Q}, '"$(top_rel_curdir)"')."
    echo "build_start(${nonce@Q}, $(date +'date_time(%Y,%m,%d,%H,%M,%S,%z)'))."
) > "${outf}"

when_done() {
    rval=$?
    echo "build_finished(${nonce@Q}, $(date +'date_time(%Y,%m,%d,%H,%M,%S,%z)'), $rval)." >> "${outf}"
}
trap when_done EXIT

"$realtool" "${@}"

