#!/usr/bin/env python3
#
# Copyright (c) 2021, General Electric Company, Inc.
#
# All Rights Reserved
#
# This material is based upon work supported by the Defense Advanced Research
# Projects Agency (DARPA) under Contract No. FA8750-20-C-0203.
#
# Any opinions, findings and conclusions or recommendations expressed in this
# material are those of the author(s) and do not necessarily reflect the views
# of the Defense Advanced Research Projects Agency (DARPA).

from Logging import *
from Evidence import *
'''

=======================================================================

    This file is Auto-Generated by GenFiles.py. 
        Any changes made to this file may be over written.

=======================================================================
'''
def ACTIVITY(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ACTIVITY"))
    objStr = "<ACTIVITY>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += "</ACTIVITY>"
    addEvidenceObject(etree.fromstring(objStr))

def AGENT(actedOnBehalfOf_identifier=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("AGENT"))
    objStr = "<AGENT>"
    objStr += objectDataString("actedOnBehalfOf_identifier", actedOnBehalfOf_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</AGENT>"
    addEvidenceObject(etree.fromstring(objStr))

def ANALYSIS(performedBy_identifier=None, dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ANALYSIS"))
    objStr = "<ANALYSIS>"
    objStr += objectDataString("performedBy_identifier", performedBy_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += "</ANALYSIS>"
    addEvidenceObject(etree.fromstring(objStr))

def ANALYSIS_ANNOTATION(annotationType_identifier=None, fromReport_identifier=None, fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ANALYSIS_ANNOTATION"))
    objStr = "<ANALYSIS_ANNOTATION>"
    objStr += objectDataString("annotationType_identifier", annotationType_identifier)
    objStr += objectDataString("fromReport_identifier", fromReport_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</ANALYSIS_ANNOTATION>"
    addEvidenceObject(etree.fromstring(objStr))

def ANALYSIS_ANNOTATION_TYPE(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("ANALYSIS_ANNOTATION_TYPE"))
    objStr = "<ANALYSIS_ANNOTATION_TYPE>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</ANALYSIS_ANNOTATION_TYPE>"
    addEvidenceObject(etree.fromstring(objStr))

def ANALYSIS_REPORT(analyzes_identifier=None, metric=None, producedBy_identifier=None, result_identifier=None, fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ANALYSIS_REPORT"))
    objStr = "<ANALYSIS_REPORT>"
    objStr += objectDataString("analyzes_identifier", analyzes_identifier)
    objStr += objectDataString("metric", metric)
    objStr += objectDataString("producedBy_identifier", producedBy_identifier)
    objStr += objectDataString("result_identifier", result_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</ANALYSIS_REPORT>"
    addEvidenceObject(etree.fromstring(objStr))

def ANALYSIS_RESULT(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("ANALYSIS_RESULT"))
    objStr = "<ANALYSIS_RESULT>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</ANALYSIS_RESULT>"
    addEvidenceObject(etree.fromstring(objStr))

def ARGUMENT_PACKAGE(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, argumentationElement_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ARGUMENT_PACKAGE"))
    objStr = "<ARGUMENT_PACKAGE>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("argumentationElement_identifier", argumentationElement_identifier)
    objStr += "</ARGUMENT_PACKAGE>"
    addEvidenceObject(etree.fromstring(objStr))

def ARGUMENT_REASONING(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ARGUMENT_REASONING"))
    objStr = "<ARGUMENT_REASONING>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</ARGUMENT_REASONING>"
    addEvidenceObject(etree.fromstring(objStr))

def ARTIFACT_REFERENCE(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ARTIFACT_REFERENCE"))
    objStr = "<ARTIFACT_REFERENCE>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</ARTIFACT_REFERENCE>"
    addEvidenceObject(etree.fromstring(objStr))

def ASSERTED_CONTEXT(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, source_identifier=None, target_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ASSERTED_CONTEXT"))
    objStr = "<ASSERTED_CONTEXT>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("source_identifier", source_identifier)
    objStr += objectDataString("target_identifier", target_identifier)
    objStr += "</ASSERTED_CONTEXT>"
    addEvidenceObject(etree.fromstring(objStr))

def ASSERTED_INFERENCE(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, reasoning_identifier=None, source_identifier=None, target_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ASSERTED_INFERENCE"))
    objStr = "<ASSERTED_INFERENCE>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("reasoning_identifier", reasoning_identifier)
    objStr += objectDataString("source_identifier", source_identifier)
    objStr += objectDataString("target_identifier", target_identifier)
    objStr += "</ASSERTED_INFERENCE>"
    addEvidenceObject(etree.fromstring(objStr))

def ASSESSING_CONFIDENCE(performedBy_identifier=None, dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ASSESSING_CONFIDENCE"))
    objStr = "<ASSESSING_CONFIDENCE>"
    objStr += objectDataString("performedBy_identifier", performedBy_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += "</ASSESSING_CONFIDENCE>"
    addEvidenceObject(etree.fromstring(objStr))

def BDU_CONFIDENCE_ASSESSMENT(assesses_identifier=None, belief=None, createBy_identifier=None, disbelief=None, uncertainty=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("BDU_CONFIDENCE_ASSESSMENT"))
    objStr = "<BDU_CONFIDENCE_ASSESSMENT>"
    objStr += objectDataString("assesses_identifier", assesses_identifier)
    objStr += objectDataString("belief", belief)
    objStr += objectDataString("createBy_identifier", createBy_identifier)
    objStr += objectDataString("disbelief", disbelief)
    objStr += objectDataString("uncertainty", uncertainty)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</BDU_CONFIDENCE_ASSESSMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def BUILD(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, step_identifier=None):
    trace()
    log("Adding Evidence:",str_good("BUILD"))
    objStr = "<BUILD>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("step_identifier", step_identifier)
    objStr += "</BUILD>"
    addEvidenceObject(etree.fromstring(objStr))

def CLAIM(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("CLAIM"))
    objStr = "<CLAIM>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</CLAIM>"
    addEvidenceObject(etree.fromstring(objStr))

def CODE_DEVELOPMENT(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, author_identifier=None, governedBy_identifier=None, referenced_identifier=None):
    trace()
    log("Adding Evidence:",str_good("CODE_DEVELOPMENT"))
    objStr = "<CODE_DEVELOPMENT>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("author_identifier", author_identifier)
    objStr += objectDataString("governedBy_identifier", governedBy_identifier)
    objStr += objectDataString("referenced_identifier", referenced_identifier)
    objStr += "</CODE_DEVELOPMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def CODE_GEN(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, performedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("CODE_GEN"))
    objStr = "<CODE_GEN>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("performedBy_identifier", performedBy_identifier)
    objStr += "</CODE_GEN>"
    addEvidenceObject(etree.fromstring(objStr))

def COLLECTION(fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("COLLECTION"))
    objStr = "<COLLECTION>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</COLLECTION>"
    addEvidenceObject(etree.fromstring(objStr))

def COMPILE(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, compileInput_identifier=None, compiledBy_identifier=None, performedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("COMPILE"))
    objStr = "<COMPILE>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("compileInput_identifier", compileInput_identifier)
    objStr += objectDataString("compiledBy_identifier", compiledBy_identifier)
    objStr += objectDataString("performedBy_identifier", performedBy_identifier)
    objStr += "</COMPILE>"
    addEvidenceObject(etree.fromstring(objStr))

def COMPONENT(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, annotations_identifier=None, componentType_identifier=None, controlFlowsToConditionally_identifier=None, controlFlowsToUnconditionally_identifier=None, definedIn_identifier=None, instantiates_identifier=None, mentions_identifier=None, name=None, requirements_identifier=None, subcomponentOf_identifier=None, valueType=None):
    trace()
    log("Adding Evidence:",str_good("COMPONENT"))
    objStr = "<COMPONENT>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("annotations_identifier", annotations_identifier)
    objStr += objectDataString("componentType_identifier", componentType_identifier)
    objStr += objectDataString("controlFlowsToConditionally_identifier", controlFlowsToConditionally_identifier)
    objStr += objectDataString("controlFlowsToUnconditionally_identifier", controlFlowsToUnconditionally_identifier)
    objStr += objectDataString("definedIn_identifier", definedIn_identifier)
    objStr += objectDataString("instantiates_identifier", instantiates_identifier)
    objStr += objectDataString("mentions_identifier", mentions_identifier)
    objStr += objectDataString("name", name)
    objStr += objectDataString("requirements_identifier", requirements_identifier)
    objStr += objectDataString("subcomponentOf_identifier", subcomponentOf_identifier)
    objStr += objectDataString("valueType", valueType)
    objStr += "</COMPONENT>"
    addEvidenceObject(etree.fromstring(objStr))

def COMPONENT_TYPE(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("COMPONENT_TYPE"))
    objStr = "<COMPONENT_TYPE>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</COMPONENT_TYPE>"
    addEvidenceObject(etree.fromstring(objStr))

def CONFIDENCE_ASSESSMENT(assesses_identifier=None, belief=None, createBy_identifier=None, disbelief=None, uncertainty=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("CONFIDENCE_ASSESSMENT"))
    objStr = "<CONFIDENCE_ASSESSMENT>"
    objStr += objectDataString("assesses_identifier", assesses_identifier)
    objStr += objectDataString("belief", belief)
    objStr += objectDataString("createBy_identifier", createBy_identifier)
    objStr += objectDataString("disbelief", disbelief)
    objStr += objectDataString("uncertainty", uncertainty)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</CONFIDENCE_ASSESSMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def DATA_DICTIONARY_TERM(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, consumedBy_identifier=None, createdBy_identifier=None, providedBy_identifier=None, text=None):
    trace()
    log("Adding Evidence:",str_good("DATA_DICTIONARY_TERM"))
    objStr = "<DATA_DICTIONARY_TERM>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("consumedBy_identifier", consumedBy_identifier)
    objStr += objectDataString("createdBy_identifier", createdBy_identifier)
    objStr += objectDataString("providedBy_identifier", providedBy_identifier)
    objStr += objectDataString("text", text)
    objStr += "</DATA_DICTIONARY_TERM>"
    addEvidenceObject(etree.fromstring(objStr))

def DESCRIPTION(dateOfIssue=None, issuingOrganization_identifier=None, references_identifier=None, status_identifier=None, fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("DESCRIPTION"))
    objStr = "<DESCRIPTION>"
    objStr += objectDataString("dateOfIssue", dateOfIssue)
    objStr += objectDataString("issuingOrganization_identifier", issuingOrganization_identifier)
    objStr += objectDataString("references_identifier", references_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</DESCRIPTION>"
    addEvidenceObject(etree.fromstring(objStr))

def DOC_STATUS(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("DOC_STATUS"))
    objStr = "<DOC_STATUS>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</DOC_STATUS>"
    addEvidenceObject(etree.fromstring(objStr))

def ENTITY(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("ENTITY"))
    objStr = "<ENTITY>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</ENTITY>"
    addEvidenceObject(etree.fromstring(objStr))

def FILE(createBy_identifier=None, fileFormat_identifier=None, fileHash_identifier=None, fileParent_identifier=None, filename=None, satisfies_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("FILE"))
    objStr = "<FILE>"
    objStr += objectDataString("createBy_identifier", createBy_identifier)
    objStr += objectDataString("fileFormat_identifier", fileFormat_identifier)
    objStr += objectDataString("fileHash_identifier", fileHash_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("filename", filename)
    objStr += objectDataString("satisfies_identifier", satisfies_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</FILE>"
    addEvidenceObject(etree.fromstring(objStr))

def FILE_CREATION(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("FILE_CREATION"))
    objStr = "<FILE_CREATION>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += "</FILE_CREATION>"
    addEvidenceObject(etree.fromstring(objStr))

def FILE_HASH(hashType_identifier=None, hashValue=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("FILE_HASH"))
    objStr = "<FILE_HASH>"
    objStr += objectDataString("hashType_identifier", hashType_identifier)
    objStr += objectDataString("hashValue", hashValue)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</FILE_HASH>"
    addEvidenceObject(etree.fromstring(objStr))

def FORMAT(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("FORMAT"))
    objStr = "<FORMAT>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</FORMAT>"
    addEvidenceObject(etree.fromstring(objStr))

def FUNCTION(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, parentFunction_identifier=None):
    trace()
    log("Adding Evidence:",str_good("FUNCTION"))
    objStr = "<FUNCTION>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("parentFunction_identifier", parentFunction_identifier)
    objStr += "</FUNCTION>"
    addEvidenceObject(etree.fromstring(objStr))

def HASH_TYPE(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("HASH_TYPE"))
    objStr = "<HASH_TYPE>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</HASH_TYPE>"
    addEvidenceObject(etree.fromstring(objStr))

def HAZARD(fileParent_identifier=None, definition=None, effect=None, identified_identifier=None, likelihood=None, severity=None, source_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("HAZARD"))
    objStr = "<HAZARD>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("definition", definition)
    objStr += objectDataString("effect", effect)
    objStr += objectDataString("identified_identifier", identified_identifier)
    objStr += objectDataString("likelihood", likelihood)
    objStr += objectDataString("severity", severity)
    objStr += objectDataString("source_identifier", source_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</HAZARD>"
    addEvidenceObject(etree.fromstring(objStr))

def HAZARD_IDENTIFICATION(author_identifier=None, dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("HAZARD_IDENTIFICATION"))
    objStr = "<HAZARD_IDENTIFICATION>"
    objStr += objectDataString("author_identifier", author_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += "</HAZARD_IDENTIFICATION>"
    addEvidenceObject(etree.fromstring(objStr))

def INTERFACE(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, destination_identifier=None, identifiedBy_identifier=None, source_identifier=None):
    trace()
    log("Adding Evidence:",str_good("INTERFACE"))
    objStr = "<INTERFACE>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("destination_identifier", destination_identifier)
    objStr += objectDataString("identifiedBy_identifier", identifiedBy_identifier)
    objStr += objectDataString("source_identifier", source_identifier)
    objStr += "</INTERFACE>"
    addEvidenceObject(etree.fromstring(objStr))

def OBJECTIVE(fileParent_identifier=None, satisfiedBy_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("OBJECTIVE"))
    objStr = "<OBJECTIVE>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("satisfiedBy_identifier", satisfiedBy_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</OBJECTIVE>"
    addEvidenceObject(etree.fromstring(objStr))

def OP_ENV(dataInsertedBy_identifier=None, description=None, identifier=None, title=None, envConstraint=None):
    trace()
    log("Adding Evidence:",str_good("OP_ENV"))
    objStr = "<OP_ENV>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += objectDataString("envConstraint", envConstraint)
    objStr += "</OP_ENV>"
    addEvidenceObject(etree.fromstring(objStr))

def OP_PROCEDURE(approvalAuthority_identifier=None, dateOfIssue=None, issuingOrganization_identifier=None, status_identifier=None, fileParent_identifier=None, mitigates_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("OP_PROCEDURE"))
    objStr = "<OP_PROCEDURE>"
    objStr += objectDataString("approvalAuthority_identifier", approvalAuthority_identifier)
    objStr += objectDataString("dateOfIssue", dateOfIssue)
    objStr += objectDataString("issuingOrganization_identifier", issuingOrganization_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("mitigates_identifier", mitigates_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</OP_PROCEDURE>"
    addEvidenceObject(etree.fromstring(objStr))

def ORGANIZATION(name=None, actedOnBehalfOf_identifier=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("ORGANIZATION"))
    objStr = "<ORGANIZATION>"
    objStr += objectDataString("name", name)
    objStr += objectDataString("actedOnBehalfOf_identifier", actedOnBehalfOf_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</ORGANIZATION>"
    addEvidenceObject(etree.fromstring(objStr))

def PACKAGE(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, packageInput_identifier=None, packagedBy_identifier=None, performedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("PACKAGE"))
    objStr = "<PACKAGE>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("packageInput_identifier", packageInput_identifier)
    objStr += objectDataString("packagedBy_identifier", packagedBy_identifier)
    objStr += objectDataString("performedBy_identifier", performedBy_identifier)
    objStr += "</PACKAGE>"
    addEvidenceObject(etree.fromstring(objStr))

def PERSON(emailAddress=None, employedBy_identifier=None, name=None, actedOnBehalfOf_identifier=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("PERSON"))
    objStr = "<PERSON>"
    objStr += objectDataString("emailAddress", emailAddress)
    objStr += objectDataString("employedBy_identifier", employedBy_identifier)
    objStr += objectDataString("name", name)
    objStr += objectDataString("actedOnBehalfOf_identifier", actedOnBehalfOf_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</PERSON>"
    addEvidenceObject(etree.fromstring(objStr))

def PLAN(approvalAuthority_identifier=None, dateOfIssue=None, issuingOrganization_identifier=None, references_identifier=None, status_identifier=None, fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("PLAN"))
    objStr = "<PLAN>"
    objStr += objectDataString("approvalAuthority_identifier", approvalAuthority_identifier)
    objStr += objectDataString("dateOfIssue", dateOfIssue)
    objStr += objectDataString("issuingOrganization_identifier", issuingOrganization_identifier)
    objStr += objectDataString("references_identifier", references_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</PLAN>"
    addEvidenceObject(etree.fromstring(objStr))

def PROCEDURE(approvalAuthority_identifier=None, dateOfIssue=None, issuingOrganization_identifier=None, status_identifier=None, fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("PROCEDURE"))
    objStr = "<PROCEDURE>"
    objStr += objectDataString("approvalAuthority_identifier", approvalAuthority_identifier)
    objStr += objectDataString("dateOfIssue", dateOfIssue)
    objStr += objectDataString("issuingOrganization_identifier", issuingOrganization_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</PROCEDURE>"
    addEvidenceObject(etree.fromstring(objStr))

def REPORT(dateOfIssue=None, issuingOrganization_identifier=None, status_identifier=None, fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("REPORT"))
    objStr = "<REPORT>"
    objStr += objectDataString("dateOfIssue", dateOfIssue)
    objStr += objectDataString("issuingOrganization_identifier", issuingOrganization_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</REPORT>"
    addEvidenceObject(etree.fromstring(objStr))

def REQUEST(dateOfInitiation=None, originatorOfRequest_identifier=None, status_identifier=None, fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("REQUEST"))
    objStr = "<REQUEST>"
    objStr += objectDataString("dateOfInitiation", dateOfInitiation)
    objStr += objectDataString("originatorOfRequest_identifier", originatorOfRequest_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</REQUEST>"
    addEvidenceObject(etree.fromstring(objStr))

def REQUIREMENT(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, createdBy_identifier=None, givenText=None, governs_identifier=None, ifText=None, mitigates_identifier=None, satisfies_identifier=None, text=None, thenText=None):
    trace()
    log("Adding Evidence:",str_good("REQUIREMENT"))
    objStr = "<REQUIREMENT>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("createdBy_identifier", createdBy_identifier)
    objStr += objectDataString("givenText", givenText)
    objStr += objectDataString("governs_identifier", governs_identifier)
    objStr += objectDataString("ifText", ifText)
    objStr += objectDataString("mitigates_identifier", mitigates_identifier)
    objStr += objectDataString("satisfies_identifier", satisfies_identifier)
    objStr += objectDataString("text", text)
    objStr += objectDataString("thenText", thenText)
    objStr += "</REQUIREMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def REQUIREMENT_DEVELOPMENT(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, author_identifier=None, governedBy_identifier=None, referenced_identifier=None):
    trace()
    log("Adding Evidence:",str_good("REQUIREMENT_DEVELOPMENT"))
    objStr = "<REQUIREMENT_DEVELOPMENT>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("author_identifier", author_identifier)
    objStr += objectDataString("governedBy_identifier", governedBy_identifier)
    objStr += objectDataString("referenced_identifier", referenced_identifier)
    objStr += "</REQUIREMENT_DEVELOPMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def REVIEW(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, author_identifier=None, governedBy_identifier=None, reviewed_identifier=None, reviewer_identifier=None):
    trace()
    log("Adding Evidence:",str_good("REVIEW"))
    objStr = "<REVIEW>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("author_identifier", author_identifier)
    objStr += objectDataString("governedBy_identifier", governedBy_identifier)
    objStr += objectDataString("reviewed_identifier", reviewed_identifier)
    objStr += objectDataString("reviewer_identifier", reviewer_identifier)
    objStr += "</REVIEW>"
    addEvidenceObject(etree.fromstring(objStr))

def REVIEW_LOG(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, createBy_identifier=None, reviewResult_identifier=None, reviews_identifier=None):
    trace()
    log("Adding Evidence:",str_good("REVIEW_LOG"))
    objStr = "<REVIEW_LOG>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("createBy_identifier", createBy_identifier)
    objStr += objectDataString("reviewResult_identifier", reviewResult_identifier)
    objStr += objectDataString("reviews_identifier", reviews_identifier)
    objStr += "</REVIEW_LOG>"
    addEvidenceObject(etree.fromstring(objStr))

def REVIEW_STATE(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("REVIEW_STATE"))
    objStr = "<REVIEW_STATE>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</REVIEW_STATE>"
    addEvidenceObject(etree.fromstring(objStr))

def SECTION(fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("SECTION"))
    objStr = "<SECTION>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</SECTION>"
    addEvidenceObject(etree.fromstring(objStr))

def SOFTWAREAGENT(actedOnBehalfOf_identifier=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("SOFTWAREAGENT"))
    objStr = "<SOFTWAREAGENT>"
    objStr += objectDataString("actedOnBehalfOf_identifier", actedOnBehalfOf_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</SOFTWAREAGENT>"
    addEvidenceObject(etree.fromstring(objStr))

def SPECIFICATION(approvalAuthority_identifier=None, dateOfIssue=None, issuingOrganization_identifier=None, references_identifier=None, status_identifier=None, fileParent_identifier=None, content_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None):
    trace()
    log("Adding Evidence:",str_good("SPECIFICATION"))
    objStr = "<SPECIFICATION>"
    objStr += objectDataString("approvalAuthority_identifier", approvalAuthority_identifier)
    objStr += objectDataString("dateOfIssue", dateOfIssue)
    objStr += objectDataString("issuingOrganization_identifier", issuingOrganization_identifier)
    objStr += objectDataString("references_identifier", references_identifier)
    objStr += objectDataString("status_identifier", status_identifier)
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("content_identifier", content_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += "</SPECIFICATION>"
    addEvidenceObject(etree.fromstring(objStr))

def SYSTEM(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, function_identifier=None, partOf_identifier=None, producedBy_identifier=None, provides_identifier=None, requires_identifier=None):
    trace()
    log("Adding Evidence:",str_good("SYSTEM"))
    objStr = "<SYSTEM>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("function_identifier", function_identifier)
    objStr += objectDataString("partOf_identifier", partOf_identifier)
    objStr += objectDataString("producedBy_identifier", producedBy_identifier)
    objStr += objectDataString("provides_identifier", provides_identifier)
    objStr += objectDataString("requires_identifier", requires_identifier)
    objStr += "</SYSTEM>"
    addEvidenceObject(etree.fromstring(objStr))

def SYSTEM_DEVELOPMENT(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, developedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("SYSTEM_DEVELOPMENT"))
    objStr = "<SYSTEM_DEVELOPMENT>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("developedBy_identifier", developedBy_identifier)
    objStr += "</SYSTEM_DEVELOPMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def TEST(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, producedBy_identifier=None, verifies_identifier=None):
    trace()
    log("Adding Evidence:",str_good("TEST"))
    objStr = "<TEST>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("producedBy_identifier", producedBy_identifier)
    objStr += objectDataString("verifies_identifier", verifies_identifier)
    objStr += "</TEST>"
    addEvidenceObject(etree.fromstring(objStr))

def TEST_DEVELOPMENT(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, developedBy_identifier=None):
    trace()
    log("Adding Evidence:",str_good("TEST_DEVELOPMENT"))
    objStr = "<TEST_DEVELOPMENT>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("developedBy_identifier", developedBy_identifier)
    objStr += "</TEST_DEVELOPMENT>"
    addEvidenceObject(etree.fromstring(objStr))

def TEST_EXECUTION(dataInsertedBy_identifier=None, description=None, endedAtTime=None, identifier=None, startedAtTime=None, title=None, used_identifier=None, wasAssociatedWith_identifier=None, wasInformedBy_identifier=None, executedOn_identifier=None):
    trace()
    log("Adding Evidence:",str_good("TEST_EXECUTION"))
    objStr = "<TEST_EXECUTION>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("endedAtTime", endedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("startedAtTime", startedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("used_identifier", used_identifier)
    objStr += objectDataString("wasAssociatedWith_identifier", wasAssociatedWith_identifier)
    objStr += objectDataString("wasInformedBy_identifier", wasInformedBy_identifier)
    objStr += objectDataString("executedOn_identifier", executedOn_identifier)
    objStr += "</TEST_EXECUTION>"
    addEvidenceObject(etree.fromstring(objStr))

def TEST_RESULT(fileParent_identifier=None, dataInsertedBy_identifier=None, description=None, generatedAtTime=None, identifier=None, invalidatedAtTime=None, title=None, wasAttributedTo_identifier=None, wasDerivedFrom_identifier=None, wasGeneratedBy_identifier=None, wasImpactedBy_identifier=None, wasRevisionOf_identifier=None, confirms_identifier=None, executedBy_identifier=None, result_identifier=None):
    trace()
    log("Adding Evidence:",str_good("TEST_RESULT"))
    objStr = "<TEST_RESULT>"
    objStr += objectDataString("fileParent_identifier", fileParent_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("generatedAtTime", generatedAtTime)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("invalidatedAtTime", invalidatedAtTime)
    objStr += objectDataString("title", title)
    objStr += objectDataString("wasAttributedTo_identifier", wasAttributedTo_identifier)
    objStr += objectDataString("wasDerivedFrom_identifier", wasDerivedFrom_identifier)
    objStr += objectDataString("wasGeneratedBy_identifier", wasGeneratedBy_identifier)
    objStr += objectDataString("wasImpactedBy_identifier", wasImpactedBy_identifier)
    objStr += objectDataString("wasRevisionOf_identifier", wasRevisionOf_identifier)
    objStr += objectDataString("confirms_identifier", confirms_identifier)
    objStr += objectDataString("executedBy_identifier", executedBy_identifier)
    objStr += objectDataString("result_identifier", result_identifier)
    objStr += "</TEST_RESULT>"
    addEvidenceObject(etree.fromstring(objStr))

def TEST_STATUS(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("TEST_STATUS"))
    objStr = "<TEST_STATUS>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</TEST_STATUS>"
    addEvidenceObject(etree.fromstring(objStr))

def THING(dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("THING"))
    objStr = "<THING>"
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</THING>"
    addEvidenceObject(etree.fromstring(objStr))

def TOOL(actedOnBehalfOf_identifier=None, dataInsertedBy_identifier=None, description=None, identifier=None, title=None):
    trace()
    log("Adding Evidence:",str_good("TOOL"))
    objStr = "<TOOL>"
    objStr += objectDataString("actedOnBehalfOf_identifier", actedOnBehalfOf_identifier)
    objStr += objectDataString("dataInsertedBy_identifier", dataInsertedBy_identifier)
    objStr += objectDataString("description", description)
    objStr += objectDataString("identifier", identifier)
    objStr += objectDataString("title", title)
    objStr += "</TOOL>"
    addEvidenceObject(etree.fromstring(objStr))

