#!/bin/sh
# Copyright (c) 2020, General Electric Company and Galois, Inc.
set -eu

./ensure-cli-in-PATH.sh

./setup-rack.sh

rack model import ../GE-Ontology/OwlModels/import.yaml

rack nodegroups import ../nodegroups/ingestion/arcos.turnstile

# Adding to script for sake of using autogenerated nodegroups (this ontology adds to base ontology which are then include in the autogenerted node groups)
rack model import ../SRI-Ontology/OwlModels/import.yaml


### Applicable Standards ### copy any of these to the instance data load script and use when applicable
# rack data import --clear ../RACK-Ontology/OwlModels/ARP-4754A.yaml     # from datagraph http://rack001/arp-475a
# rack data import --clear ../RACK-Ontology/OwlModels/DO-330.yaml        # from datagraph http://rack001/do-330
rack data import --clear ../RACK-Ontology/OwlModels/DO-178C.yaml         # from datagraph http://rack001/do-178c
# rack data import --clear ../RACK-Ontology/OwlModels/MIL-STD-881D.yaml  # from datagraph http://rack001/mil-std-881d
