# This file is intended to be used using the rack.py script found
# in RACK-Ontology/scripts/
#
# Script documentation is available in RACK-Ontology/scripts/README.md
data-graph: "http://rack001/data"
ingestion-steps:
- { owl: "ARP-4754A.owl"}
- { owl: "DO-178C.owl"}
- { owl: "DO-330.owl"}
- { owl: "MIL-STD-881D.owl"}       
- { owl: "MIL-STD-881D-AppxB.owl"}
- { owl: "MIL-STD-881D-AppxD.owl"}
- { owl: "MIL-STD-881D-AppxA.owl"}
- { owl: "MIL-STD-881D-AppxC.owl"}
