class Fore:
    @property
    def BLUE(self) -> str: ...
    @property
    def CYAN(self) -> str: ...
    @property
    def GREEN(self) -> str: ...
    @property
    def MAGENTA(self) -> str: ...
    @property
    def RED(self) -> str: ...
    @property
    def WHITE(self) -> str: ...
    @property
    def YELLOW(self) -> str: ...
