#!/usr/bin/env bash
# shellcheck disable=SC2184,SC2027,SC2046,SC2162,SC1090
#
# Copyright (c) 2020, General Electric Company and Galois, Inc.

. $(dirname "$0")/rackfuncs.sh

tool=$(basename "$0")
realtool=$(find_in_path_remainder "$tool")
nonce="n$(date +%s)-$$"

archive_file_idx=2
creating=0
# shellcheck disable=SC2086,SC2048
read -a files < <(echo ${*})
unset files[0]
unset files[1]


if grep -q a <(echo "$1") ; then
    archive_file_idx=3
elif grep -q b <(echo "$1") ; then
    archive_file_idx=3
fi

if grep -q c <(echo "$1"); then
    creating=1
elif grep -q q <(echo "$1"); then
    creating=1
elif grep -q r <(echo "$1"); then
    creating=1
fi

if (( creating )) ; then
    outf=${!archive_file_idx}
    rackf="$(dirname "${outf}")/.$(basename "${outf}").rack"

    (
        export IFS=","
        shift $archive_file_idx
        shift 1
        rack_info_pre "ar"
        echo "build_inputs(${nonce@Q}, [ ${*@Q} ])."
        echo "build_outputs(${nonce@Q}, [ ${outf@Q} ])."
    ) > "${rackf}"

    update_make_steps

    when_done() {
        rack_info_post >> "${rackf}"
        for F in "${files[@]}" "$realtool" ; do
            read sum f < <(sha1sum "$F")
            echo "file_sha1(${f@Q}, ${sum@Q}, ${nonce@Q})." >> "${rackf}"
        done
    }
    trap when_done EXIT

    echo "${rackf}" >> /tmp/ar.log
fi

"$realtool" "${@}"

