#!/usr/bin/env bash
# shellcheck disable=SC1090,SC2046
#
# Copyright (c) 2020, General Electric Company and Galois, Inc.

. $(dirname "$0")/rackfuncs.sh

outf=$(pwd)/.make.rack
tool=$(basename "$0")
realtool=$(find_in_path_remainder "$tool")
nonce="n$(date +%s)-$$"

# This flag can be used by the databin handlers of the commands
# invoked by make to link those commands to this make process.
export MAKE_DATABIN="${outf}@${nonce}:${MAKE_DATABIN}"

rack_info_pre "make" "${@}" > "${outf}"

when_done() {
    rack_info_post >> "${outf}"
}
trap when_done EXIT

"$realtool" "${@}"

