#!/usr/bin/env bash
# shellcheck disable=SC2166,SC2046,SC1090
#
# Copyright (c) 2020, General Electric Company and Galois, Inc.

. $(dirname "$0")/rackfuncs.sh

tmpfile=".$$.strace"
nonce="n$(date +%s)-$$"
realtool=$(find_in_path_remainder $(basename "$0"))

update_make_steps

on_finish() {
    rm -f ${tmpfile}*
}
trap on_finish EXIT ERR

echo ":- multifile tar_start/3, tar_finished/3, tar_access/3,
                   build_from/2, build_user/2, file_sha1/3, file_committer/2." > ${tmpfile}.out
echo "tar_start(${nonce@Q}, $(date +'date_time(%Y,%m,%d,%H,%M,%S,%z)'), ${realtool@Q})." >> ${tmpfile}.out
echo "build_user(${nonce@Q}, '$(whoami)')." >> ${tmpfile}.out

strace -f -e trace=file -e status=successful -o "$tmpfile" "$realtool" "${@}"

rval=$?
echo "tar_finished(${nonce@Q}, $(date +'date_time(%Y,%m,%d,%H,%M,%S,%z)'), $rval)." >> ${tmpfile}.out

awk -f <(
    cat <<EOF
BEGIN { show=0;
        print "build_from(${nonce@Q}, '$(top_rel_curdir)').";
      }
/creat/ {
    split(\$2, p, "(");
    if (show==0) {
      # Unique name for output file, based on first tar output file
      name = p[2]
      gsub("\"", "", name)
      gsub(",$", "", name)
      print name >"${tmpfile}.name"
      # Initialization command
    }
    show=1;
    unquoted_fname = substr(p[2], 0, length(p[2])-1)
    gsub("\"", "", unquoted_fname)
    print "tar_access('${nonce}', '" unquoted_fname "', create)."
    "sha1sum " name | getline shafilesum
    split(shafilesum, sha)
    print "file_sha1('" sha[2] "', '" sha[1] "', '${nonce}')."
  }
/openat/ { if (show==1) {
             name = \$3
             gsub(",$", "", name)
             unquoted_name = name
             gsub("\"", "", unquoted_name)
             print "tar_access('${nonce}', '" unquoted_name "', open)."
             "sha1sum " name | getline shafilesum
             split(shafilesum, sha)
             gitauth = "git log -n 1 --pretty=format:\"file_committer('" unquoted_name "', '%al').\" " name " 2>/dev/null" | getline
             if (gitauth != 0) print
             print "file_sha1('" sha[2] "', '" sha[1] "', '${nonce}')."
           }
         }
EOF
        )  $tmpfile >> $tmpfile.out

if [ -r $tmpfile.out -a -r $tmpfile.name ] ; then
    mv $tmpfile.out .$(cat $tmpfile.name).rack
    rm $tmpfile.name
fi
