#!/usr/bin/env bash

# TODO: use -M for internal assist of include files
# TODO: get -L paths and -l libraries

$(dirname $0)/rackfuncs.sh

inf=()
outf=''
opts=()

outnxt=0

for ARG ; do
    case ${ARG} in
        -o) outnxt=1 ;;
        *) if (( $outnxt )) ; then
               outf="${ARG}"
               outnxt=0
           elif [ -r ${ARG} ] ; then
               inf+=("${ARG}")
           else
               opts+=("${ARG}")
           fi
           ;;
    esac
done

outf="${outf:-$(basename $inf .c).o}"
tool=$(basename $0)
realtool=$(find_in_path_remainder $tool)

(
    export IFS=","
    nonce="n$(date +%s)-$$"
    echo ":- multifile build_with/5, build_from/2, build_inputs/2, build_outputs/2."
    echo "build_with(${nonce@Q}, compile," ${tool@Q}, ${realtool@Q}, [ "${opts[*]@Q}" ] ")."
    echo "build_from(${nonce@Q}, '"$(pwd)"')."
    echo "build_inputs(${nonce@Q}, [ ${inf[*]@Q} ])."
    echo "build_outputs(${nonce@Q}, [ ${outf@Q} ])."

) > .${outf}.rack

$realtool ${*}
