#!/usr/bin/env bash

. $(dirname $0)/rackfuncs.sh

tool=$(basename $0)
realtool=$(find_in_path_remainder $tool)
nonce="n$(date +%s)-$$"

# This flag can be used by the databin handlers of the commands
# invoked by make to link those commands to this make process.
export MAKE_DATABIN="$nonce"

(
    echo ":- multifile build_with/5, build_from/2, build_inputs/2, build_outputs/2, build_start/2, build_finished/3."
    echo "build_with(${nonce@Q}, make," ${tool@Q}, ${realtool@Q}, [ "${opts[*]@Q}" ] ")."
    echo "build_from(${nonce@Q}, '"$(top_rel_curdir)"')."
    echo "build_start(${nonce@Q}, $(date +'date_time(%+4Y,%m,%d,%H,%M,%S,%z)'))."
) > .make.rack

when_done() {
    rval=$?
    echo "build_finished(${nonce@Q}, $(date +'date_time(%+4Y,%m,%d,%H,%M,%S,%z)'), $rval)." >> .make.rack
}
trap when_done EXIT

$realtool ${*}

