# Lints the RACK source upon every push (while ignoring tag-only pushes)

name: RACK continous lint

on:
  pull_request:
    branches: [ '*' ]
  push:
    branches: [ '*' ]
    tags-ignore: [ '*' ]

jobs:
  lint:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out RACK source
      uses: actions/checkout@v2

    - name: Cache development dependencies
      uses: actions/cache@v2
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit for the corresponding requirements file
        key: ${{ runner.os }}-pip-${{ hashFiles('cli/dev/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install development dependencies
      run: pip3 install -q -r cli/dev/requirements.txt

    - name: Lint RACK CLI
      run: |
        cd cli
        pylint .
        mypy .

    - name: Lint RACK Ontology
      run: |
        sudo apt-add-repository ppa:swi-prolog/stable
        sudo apt-get update -qq --yes
        sudo apt-get install -qq --yes swi-prolog
        ./assist/bin/check

    - name: Lint shell scripts
      # This action is composite on master which `act` can't yet handle.
      uses: ludeeus/action-shellcheck@fcee962fee3f87888d7992ab0560232aef368e89
      env:
        SHELLCHECK_OPTS: -e SC1008
