# Runs after every change to nodegroups/queries/store_data.csv on master branch

name: RACK Update Wiki Workflow
on:
  push:
    branches: [ master ]
    paths:
      - 'nodegroups/queries/store_data.csv'

jobs:

# update-wiki job:
#  - Updates RACK-Predefined-Queries.md in RACK.wiki

  update-wiki:
    runs-on: ubuntu-20.04

    steps:
    - name: Check out RACK source
      uses: actions/checkout@v3
      with:
        repository: ge-high-assurance/RACK
        path: RACK

    - name: Check out RACK wiki
      uses: actions/checkout@v3
      with:
        repository: ge-high-assurance/RACK.wiki
        path: RACK.wiki
        
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.8

    - name: Cache Python dependencies
      uses: actions/cache@v3
      with:
        # This path is specific to Ubuntu
        path: ~/.cache/pip
        # Look to see if there is a cache hit
        key: ${{ runner.os }}-pip-csvtomd
        restore-keys: |
          ${{ runner.os }}-pip-
          ${{ runner.os }}-

    - name: Install csvtomd
      run: |
        pip3 install csvtomd --user
      
    - name: Update query wiki page
      run: |
        csvtomd RACK/nodegroups/queries/store_data.csv > temp.md
        cat RACK.wiki/_RACK-Predefined-Queries-header.md temp.md RACK.wiki/_RACK-Predefined-Queries-footer.md > RACK.wiki/RACK-Predefined-Queries.md
        cd RACK.wiki
        git config user.name github-actions
        git config user.email github-actions@github.com
        git add .
        git commit -m "Update RACK-Predefined-Queries.md"
        git push
