# pylint: skip-file

class Fore:
    @property
    def BLUE(self) -> str: ...
    @property
    def CYAN(self) -> str: ...
    @property
    def GREEN(self) -> str: ...
    @property
    def MAGENTA(self) -> str: ...
    @property
    def RED(self) -> str: ...
    @property
    def RESET(self) -> str: ...
    @property
    def WHITE(self) -> str: ...
    @property
    def YELLOW(self) -> str: ...

class Style:
    @property
    def BRIGHT(self) -> str: ...
    @property
    def RESET_ALL(self) -> str: ...
